### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by calispac**
Trying to adress the open issues

### CODE REVIEW

**Comment by calispac** [comment]
Solves #6

**Comment by dneise** [comment]
it says: small fixes but 16 files ... phew .. reviewing now.
Would maybe be good to fix the pep8 issues in the meantime if you have time

**Comment by calispac** [comment]
Ok now all pep8 remaining issues are caused by docopt. For instance I don't know how to write this : 
https://github.com/cta-sst-1m/digicamscheduling/blob/782c6f042ee7a51caeadf9162cfa09e6e09f8f92/digicamscheduling/scripts/catalog.py#L22
without breaking docopt.

**Comment by calispac** [comment]
I would like to include in this PR a different color map / markers for every source. My problem is that I don't really know a good solution for that. I mean how can we make a plot with N distinguishable colors/markers ? This is how it is done at the moment : 

https://github.com/cta-sst-1m/digicamscheduling/blob/782c6f042ee7a51caeadf9162cfa09e6e09f8f92/digicamscheduling/scripts/elevation.py#L83-L88
And people are not really happy with the choice of colormap

**Pull request merged**
